delay_per_char: 0.5
enable_split: true
# 需要保留的标点符号列表
# 这些标点符号会在显示时保留
keep_punctuation:
- ？
- ！
- '?'
- '!'
- '~'
- 〜
# 达到该字符数时将不进行分段
max_chars_for_split: 100
# 需要删除的标点符号列表
# 这些标点符号会在处理时被忽略
skip_punctuation:
- ，
- 。
- ','
- .
- ':'
- ：
- \n
# 用于分段的标点符号列表
# 遇到这些符号时会将文本分成多段发送
split_punctuation:
- ？
- ！
- '?'
- '!'
- '~'
- 〜
