# 每个字符的延迟时间(秒)，控制打字速度
delay_per_char: 0.5

# 是否启用分段发送功能
# true: 启用  false: 禁用
enable_split: true

# 需要保留的标点符号列表
# 这些标点符号会在显示时保留
keep_punctuation:
- ？  # 中文问号
- ！  # 中文感叹号
- '?'  # 英文问号(需用引号包裹)
- '!'  # 英文感叹号(需用引号包裹)
- 〜  # 中文波浪线

# 需要删除的标点符号列表
# 这些标点符号会在处理时被忽略
skip_punctuation:
- ，  # 中文逗号
- 。  # 中文句号
- ','  # 英文逗号(需用引号包裹)
- .  # 英文句号
- ':'  # 英文冒号
- ：  # 中文冒号
- '

  '  # 换行符(需用引号包裹)

# 用于分段的标点符号列表
# 遇到这些符号时会将文本分成多段发送
split_punctuation:
- ？  # 中文问号
- ！  # 中文感叹号
- '?'  # 英文问号(需用引号包裹)
- '!'  # 英文感叹号(需用引号包裹)
